### ISSUE TITLE
Installation does not work with `strapi install import-content`

### ISSUE THREAD

**Issue by jbeuckm** [jbeuckm/strapi-plugin-import-content#11]
```
✖ An error occurred during plugin installation.
Please make sure this plugin is available on npm: https://www.npmjs.com/package/strapi-plugin-import-content
```

The package does appear at that url on npm, but this installation method is not working.

**Comment by derrickmehaffy** [comment]
@jbeuckm Strapi hasn't fully designed their plan yet with regards to the internal CLI/AdminUI options for 3rd party plugins, they do plan to support it but they will need to build out their marketplace structure.

Right now the plugins are pulled from: https://marketplace.strapi.io/plugins so in the future my guess is they would have a place were you can submit your plugin (along with any options for making it paid for, private npm repo settings, ect)

Their beta release is due within the next month or two and I would fully expect some headway to be made on the marketplace within the next few months (I'm guessing Q3 2019)

**Comment by jbeuckm** [comment]
Closing issue since this is impossible right now.
